# Generated by Django 2.1.2 on 2018-11-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
