# Generated by Django 2.1.2 on 2018-11-22 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0004_auto_20181122_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 2, 53, 55, 928828)),
        ),
    ]
