# Generated by Django 2.1.2 on 2018-11-22 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0005_auto_20181122_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
