# Generated by Django 2.1.2 on 2018-11-26 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0006_auto_20181122_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delay',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 5, 31, 691793)),
        ),
    ]
