# Generated by Django 2.1.2 on 2018-11-26 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0007_auto_20181126_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
