# Generated by Django 2.1.2 on 2018-11-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0008_auto_20181126_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delay',
            field=models.IntegerField(null=True),
        ),
    ]
