# Generated by Django 2.1.2 on 2018-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0010_auto_20181126_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='launches_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
