# Generated by Django 2.1.2 on 2018-11-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0011_task_launches_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walker_panel.Task'),
        ),
    ]
