# Generated by Django 2.1.2 on 2018-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0012_log_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='extra',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.TextField(default='INFO'),
        ),
    ]
