# Generated by Django 2.1.2 on 2018-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0014_auto_20181130_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='uid',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
