# Generated by Django 2.1.2 on 2018-12-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0016_auto_20181130_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='region',
        ),
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='extra',
            field=models.TextField(default='', null=True),
        ),
    ]
