# Generated by Django 2.1.2 on 2018-12-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0018_auto_20181203_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
