# Generated by Django 2.1.2 on 2018-12-05 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walker_panel', '0019_proxy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('owner', 'host', 'port')},
        ),
    ]
