# Generated by Django 2.1.2 on 2018-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_panel', '0020_auto_20181205_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
