# Generated by Django 2.1.2 on 2018-10-28 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('proxy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('host', models.TextField()),
                ('port', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
