# Generated by Django 2.1.2 on 2018-10-28 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyModel',
            fields=[
                ('proxy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('host', models.TextField()),
                ('port', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('enabled', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
    ]
