# Generated by Django 2.1.2 on 2018-10-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker', '0004_auto_20181029_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
