# Generated by Django 2.1.2 on 2018-11-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker', '0007_auto_20181104_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set(),
        ),
    ]
