# Generated by Django 2.1.2 on 2018-11-05 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walker', '0008_auto_20181105_0131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('owner', 'host', 'port', 'username')},
        ),
    ]
