# Generated by Django 2.1.2 on 2018-11-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walker', '0009_auto_20181105_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='competitors_sites',
            new_name='competitor_sites',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='target_site',
            new_name='target_url',
        ),
    ]
